env: flex
runtime: nodejs

beta_settings:
  cloud_sql_instances: digitalskillshub:us-central1:digital-skills

env_variables:
  SECRET: secret
  SENDGRID_KEY: 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
  FCM_SERVER_KEY: AAAATtabi8g:APA91bFvAWz5t9QvXoIerNAvOhj0wJryvDBtNKVv6FJKmx9y59fjU2fFDUyNsaFQ9d4P4sLVKukbbvHeQOGRYNMbNIAsT0YsEsPAhxqEqrt0rS5JXTxyA6YTLm47X9BAz9qs7LlV4aFe
  DB_USERNAME: admin,
  DB_PASSWORD: admin,
  DB_DATABASE: digital_skills,
  DB_HOST: localhost,
  DB_PORT: 5432,
