env: flex
runtime: nodejs
env_variables:
  SECRET: secret

  DB_USERNAME: llisqeskkpsjnm
  DB_PASSWORD: 77cbf9a001f16f67762f421a59cfdb5647e6e5edc3913ef05f531991f5f82e2d
  DB_DATABASE: d3be8scrv9d5jc
  DB_HOST: ec2-107-21-120-104.compute-1.amazonaws.com
  DB_PORT: 5432

  SENDGRID_KEY: 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

  CLOUDINARY_CLOUD_NAME: veda
  CLOUDINARY_API_KEY: 632537659423521
  CLOUDINARY_API_SECRET: Pmq3Dd-cLPsAW3XW9tRrwIjyXx4

  FCM_SERVER_KEY: AAAATtabi8g:APA91bFvAWz5t9QvXoIerNAvOhj0wJryvDBtNKVv6FJKmx9y59fjU2fFDUyNsaFQ9d4P4sLVKukbbvHeQOGRYNMbNIAsT0YsEsPAhxqEqrt0rS5JXTxyA6YTLm47X9BAz9qs7LlV4aFe
