env: flex
includes:
  - env_variables.yaml
runtime: nodejs
threadsafe: yes

beta_settings:
  cloud_sql_instances: gdsa-120b6:europe-west1:gdsa

skip_files:
 - ^node_modules$
 - ^.git$

automatic_scaling:
  min_num_instances: 3

